### ISSUE TITLE
[feature request] Support  group and pear modifiers.

### ISSUE THREAD

**Issue by vermutely** [pintariching/railwind#10]
Support for the following modifiers provided by TailwindCSS.
- [Styling based on parent state (group-{modifier})](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state)
- [Styling based on sibling state (peer-{modifier})](https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state)
-----

Are there any current plans to add this feature?

**Comment by pintariching** [comment]
I plan for railwind to be a 1:1 with tailwind, if possible even better. For now I haven't looked much at the other features but the classes, but yes, I plan to have support for every feature that tailwind has.
