### ISSUE TITLE
Add more tests for all the classes

### ISSUE THREAD

**Issue by pintariching** [pintariching/railwind#18]
Add test for all of the  rest of the implemented classes. I used [tailwind play](https://play.tailwindcss.com/) to get the expected output and put it into `expected.css`, then copy the input into `input.html` and the `output.css` should be automatically generated.

Sometimes the order of the generated CSS classes differs from the `tailwind` expected input, so reordering the `expected.css` classes is allowed. 

I also put arbitrary classes at the end of `input.html` for every class that supports it.

- [x] Layout
- [x] Flexbox & Grid
- [x] Spacing
- [x] Sizing
- [x] Typography
- [x] Backgrounds
- [x] Borders
- [x] Effects
- [x] Filters
- [x] Tables
- [x] Transitions & Animations
- [x] Transforms
- [x] Interactivity
- [x] SVG
- [x] Accessibility

**Comment by vermutely** [comment]
I noticed the difference in behavior when I was writing the test code.
Can I align with Tailwind Play behavior?

## Example

### Tailwind Play

<img width="980" alt="Tailwind Play" src="https://user-images.githubusercontent.com/120990970/210467792-76a9e72a-6404-4bf1-9f1e-e6bd2107c744.png">

### Railwind

<img width="487" alt="Railwind" src="https://user-images.githubusercontent.com/120990970/210467903-78ab9288-55d7-46ed-8df4-2527d74767cd.png">

**Comment by pintariching** [comment]
Yeah sure! A lot of the time, Tailwind adds declarations like this, that are not written in the documentation, so the only way to know is with Tailwind Play. That's also why we write tests 😁.

**Comment by pintariching** [comment]
Okay awesome, thank you for the tests! We're moving forward at a blistering pace!
