### ISSUE TITLE
Usage as a library needs some adjustements

### ISSUE THREAD

**Issue by yamafaktory** [pintariching/railwind#31]
Hi,

There are two minors issues folks can potentially face when using the tool as a library (me included 😄 ):
- the `Warning` struct is not explosed in the `lib.rs` so this make it difficult to deal with it
- the `preflight.css` asset should be included at compile time using e.g. `include_str!` (e.g.https://github.com/pintariching/railwind/blob/eec138c3a3e693cb4e61f53f0e8e7ff94ee9e9f8/railwind/src/lib.rs#L185) because now it panics when toggling the bool to true (which makes sense since the file doesn't exist)

**Comment by pintariching** [comment]
Now that you mention it, I don't know whyI haven't thought about this 😅. Thanks for bringing it up, I'll fix the issue shortly.

**Comment by pintariching** [comment]
Okay I think I fixed these issues in the `0.0.10` version of the CLI.
