### ISSUE TITLE
Add option to include vendor specific prefixes to output CSS file

### ISSUE THREAD

**Issue by austinlucaslake** [pintariching/railwind#41]
Vendor specific prefixes:
`-webkit`, `-moz`, `-mz`, `-o`, etc.

**Comment by pintariching** [comment]
Vendor specific prefixes are automatically added when you use a class that requires them. What did you have in mind?

**Comment by austinlucaslake** [comment]
I was doing some work for my personal website and I was trying to apply the `grayscale` class to some images. However, it wasn't being applied properly because only the `filter` class as produced on the css file. When I manually edited the css file to include `-webkit-filter`, the grayscale option was applied properly.

**Comment by pintariching** [comment]
That's strange. Playing around with with [Tailwind Play the grayscale seems to work ok](https://play.tailwindcss.com/EtOHI6Lst2). The filters do some stuff with CSS variables. Have you used the preflight `-p` option?

**Comment by austinlucaslake** [comment]
I do see some vendor specific prefixes for tags other than grayscale. For context I am using Google Chrome and was loading my CSR website using the `trunk` crate. I suspect it must stem from that in some fashion. I even tried TailwindCSS proper, and it was giving me a similar result when loading with trunk. I will go ahead a close this issue as I don't believe it to be a railwind specific problem.
