### ISSUE TITLE
[question] Multiple definitions of the same class are generated.

### ISSUE THREAD

**Issue by vermutely** [pintariching/railwind#7]
I found that the same class is generated when I am working on adding a classes.
The following sample generates multiple w-full classes.

### Tailwind Play
<img width="693" alt="Tailwind Play" src="https://user-images.githubusercontent.com/120990970/210070354-c5c38500-40b2-4caa-83e8-7636010a04d3.png">

### Railwind
<img width="556" alt="Railwind" src="https://user-images.githubusercontent.com/120990970/210070388-37a0455a-6831-4ee4-8850-b8ffc3c2a0f3.png">

## Question
This behavior differs from Tailwind Play. Do you have any plans to fix?

If the maintainer is busy with a scheduled fix, I can make arrangements to see if I can handle it.

**Comment by pintariching** [comment]
How could I miss something so obvious. Thanks for the heads up, I'll look into it, this should definetly be fixed.

**Comment by vermutely** [comment]
@pintariching 
Thank you very much for the swift reply.

If you are busy, please assign me a job.
I would love to support this great project.

**Comment by pintariching** [comment]
Okay I think I fixed this now. Before I used a `Vec` to store all the classes, now I'm using an `IndexMap` to preserve the order to pass the tests and to remove duplicate classes if they happen.
